# Site settings
name: 笑东风
email: gaojia2004@hotmail.com
author: 笑东风
url: https://gaogao67.github.io/
resume_site: https://gaogao67.github.io/
github: https://github.com/gaogao67
baseurl: ""
description: 身在凡尘，笑在东风！
meta_description: 笑东风博客
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:categories/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: gaogao67

# Build settings
markdown: kramdown


