# Site settings
name: 笑东风
email: gaojia2004@hotmail.com
author: 笑东风
url: https://gaogao67.github.io/
resume_site: https://gaogao67.github.io/
github: https://github.com/gaogao67
baseurl: ""
description: Just do it！
meta_description: 笑东风博客
motto: "生死看淡，不服就干。"
banner: "多做事，少哔哔。"

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:categories/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: gaogao67

# Build settings
markdown: kramdown


